config/routes.rb
Rails.application.routes.draw do
  scope ':username' do
    get 'feed' => 'users#feed'
    get 'following' => 'users#following'
    get 'followers' => 'users#followers'

    resources :albums, only: [:index, :show, :create, :update, :destroy]
    resources :albums, only: [] do
      resources :photos
    end

    resources :photos, only: [] do
      resources :comments, only: [:create, :destroy]
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'users/registrations'
  }

  get 'search' => 'users#index'
  resources :relationships, only: [:create, :destroy]

  get 'try' => 'static_pages#login_as_default_user'
  root 'static_pages#welcome'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :albums, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, {
    class_name: 'Relationship',
    foreign_key: 'follower_id',
    dependent: :destroy }
  has_many :passive_relationships, {
    class_name: 'Relationship',
    foreign_key: 'followed_id',
    dependent: :destroy }
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, 
    :registerable,
    :recoverable,
    :rememberable,
    :trackable,
    :validatable,
    #confirmable,
    :lockable,
    :omniauthable
  mount_uploader :avatar, UserAvatarUploader

  validates :full_name, length: { maximum: 128 }

  def self.from_omniauth(auth)
    where(omni_provider: auth.provider, omni_uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email || Faker::Internet.email
      user.full_name = auth.info.name || auth.info.nickname
      user.password = Devise.friendly_token[0,20]
    end
  end

  def following?(user)
    following.include? user
  end

  def follow(other_user)
    active_relationships.create followed_id: other_user.id
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def count_of_followers
    followers.count
  end

  def count_of_following
    following.count
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  skip_before_action :set_username

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
    def update
      super
    end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:avatar,
								:remote_avatar_url,
								:gravatar,
								:full_name])
    end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_username, except: :index
  OBJECTS_ON_PAGE = 20

  def index
    @users = search(params[:search])
  end

  def feed
    @page = params[:page].to_i
    all = []
    %w[ photos comments albums ].each do |obj|
      find_objects(obj).each do |o|
	all << o
      end
    end
    all = all.sort { |a,b| b.updated_at <=> a.updated_at }
    @objects = all[@page * OBJECTS_ON_PAGE,OBJECTS_ON_PAGE]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def following
    @users = find_user.following
  end

  def followers
    @users = find_user.followers
  end

  private

  def search(keywords)
    User.where('full_name ilike ? and full_name != ?', "%#{keywords}%", current_user.full_name)
  end

  def find_objects(objects)
    result = []
    followings_objects = []
    own_objects = extract_objects(find_user, objects)
    find_user.following.each do |following|
      followings_objects << extract_objects(following, objects)
    end
    [own_objects, followings_objects.flatten].each do |obj|
      obj.each { |o| result << o }
    end
    result
  end

  def extract_objects(user, table)
    case table
    when 'photos'
      user.photos
    when 'albums'
      user.albums
    when 'comments'
      user.comments
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def author(user)
    if snake_case(user.full_name) == @username then 'You' else user.full_name end
  end

  def possessive_words(comment)
    author_of_comment = comment.owner_name
    author_of_photo = author(comment.photo.user)
    if author_of_comment == author_of_photo
      'personal'
    elsif author_of_photo == 'You'
      'your'
    else
      "#{author_of_photo}'s"
    end
  end
end

app/views/users/_feed_album.html.haml
.feed_album
  .panel.panel-info
    .panel-heading
      = time_ago_in_words(album.updated_at)
      ago:
      = author(album.user)
      - if album.updated_at > album.created_at
        updated album
      - else
        created new album
    .panel-body
      .row
        .col-sm-6
          = link_to album_url(snake_case(album.owner_name), album) do
            - url = if album.photos.empty? then '' else album.newest_photo_thumb end
            = image_tag url, style: 'max-width: 100%'
        .col-sm-6
          %h2.h4= album.title
          %hr
          %p= pluralize(album.photos_count, 'photo')

app/views/users/_feed_comment.html.haml
.feed_comment
  .panel.panel-default
    .panel-heading
      = time_ago_in_words(comment.updated_at)
      ago:
      = author(comment.user)
      commented
      = possessive_words(comment)
      photo
      = link_to comment.photo_title, album_photo_url(snake_case(comment.photo_owner_name), comment.photo_album, comment.photo), style: 'font-weight: bold'
    .panel-body
      .row
        .col-md-6
          = render partial: 'comments/comment', object: comment

app/views/users/_feed_loader.html.haml
= link_to 'More',
  feed_url(username: snake_case(current_user.full_name), page: (@page + 1)),
  remote: true, class: 'btn btn-primary btn-lg btn-block'

app/views/users/_feed_photo.html.haml
.feed_photo
  .panel.panel-primary
    .panel-heading
      = time_ago_in_words(photo.updated_at)
      ago:
      = author(photo.user)
      - if photo.updated_at > photo.created_at
        updated photo
      - else
        added new photo
    .panel-body
      .row
        .col-xs-6
          = link_to album_photo_url(snake_case(photo.owner_name), photo.album, photo) do
            = image_tag photo.thumb_url, style: 'max-width: 100%'
        .col-xs-6
          %h2.h4= photo.title
          %p= photo.caption
          %hr
          %p
            Album: 
            = link_to album_url(snake_case(photo.owner_name), photo.album) do
              = photo.album_title
          %p= pluralize(photo.comments_count, 'comment')

app/views/users/_follow.html.haml
= simple_form_for(current_user.active_relationships.build) do |f|
  = hidden_field_tag :followed_id, user.id
  = f.button :submit, 'Follow', class: 'btn btn-primary'

app/views/users/_object.html.haml
- @objects.each do |object|
  - if object.respond_to? :source
    = render partial: 'users/feed_photo', locals: { photo: object }
  - elsif object.respond_to? :body
    = render partial: 'users/feed_comment', locals: { comment: object }
  - else
    = render partial: 'users/feed_album', locals: { album: object }

app/views/users/_unfollow.html.haml
= simple_form_for(current_user.active_relationships.find_by(followed_id: user.id), html: {method: :delete}) do |f|
  = f.button :submit, 'Unfollow', class: 'btn'

app/views/users/_user.html.haml
.thumbnail
  = avatar_for user
  .caption
    .text-center= user.full_name
    - unless user == current_user
      %hr
      = link_to albums_url(snake_case(user.full_name)), class: 'btn btn-primary pull-right' do
        Albums
        %span.badge= user.albums.count
      = link_to 'Feed', feed_url(snake_case(user.full_name)), class: 'btn btn-link'
      %hr{style: 'width: 50%; margin-left: 0'}
      - if current_user.following? user
        = render partial: 'unfollow', locals: { user: user }
      - else
        = render partial: 'follow', locals: { user: user }

app/views/users/feed.html.haml
%ol.breadcrumb
  %li.active= full_name_from_params(@username)

%header#feed-links
  %ul.nav.nav-tabs{data: {spy: 'affix', offset_top: '150'}}
    %li.active#all
      %a{href: '#show-all'} All
    %li#photos
      %a{href: '#show-photos'} Photos
    %li#albums
      %a{href: '#show-albums'} Albums
    %li#comments
      %a{href: '#show-comments'} Comments
%br
#feed
  = render partial: 'users/object'

- if @objects.blank?
  %h2 You'll see your activities here, create a new album for beginning
- else
  %hr
  #feed-loader{style: 'margin-bottom: 100px'}
    = render 'users/feed_loader'

app/views/users/feed.js.haml
$("#{escape_javascript(render 'users/object')}").appendTo("#feed");
$("#feed-loader").html("#{escape_javascript(render 'users/feed_loader')}");
$("#feed-links .active a").click();

app/views/users/followers.html.haml
%ol.breadcrumb
  %li
    %a{href: feed_url(@username)}= full_name_from_params(@username)
  %li.active Followers

.masonry
  = render @users

app/views/users/following.html.haml
%ol.breadcrumb
  %li
    %a{href: feed_url(@username)}= full_name_from_params(@username)
  %li.active Following

.masonry
  = render @users

app/views/users/index.html.haml
%ol.breadcrumb
  %li.active Search for #{params[:search]} among users

.masonry
  = render @users