config/routes.rb
Rails.application.routes.draw do
  scope ':username' do
    get 'feed' => 'users#feed'
    get 'following' => 'users#following'
    get 'followers' => 'users#followers'

    resources :albums, only: [:index, :show, :create, :update, :destroy]
    resources :albums, only: [] do
      resources :photos
    end

    resources :photos, only: [] do
      resources :comments, only: [:create, :destroy]
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'users/registrations'
  }

  get 'search' => 'users#index'
  resources :relationships, only: [:create, :destroy]

  get 'try' => 'static_pages#login_as_default_user'
  root 'static_pages#welcome'
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos, dependent: :destroy
  default_scope -> { order(updated_at: :desc) }

  validates :user_id, presence: true
  validates :title, length: { maximum: 128 }

  def newest_photo_thumb
    photos.first.thumb_url
  end

  def photos_count
    photos.count
  end

  def owner_name
    user.full_name
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :update, :destroy]
  before_action :set_username

  def index
    @albums = find_user.albums
  end

  def show
    redirect_to album_photos_url(@username, @album)
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:notice] = "Album '#{@album.title}' has been successfully created"
    else
      flash[:alert] = "Ooops, something went wrong, album has not been saved. Repeat with other options"
    end
    redirect_to album_url(@username, @album)
  end

  def update
    if @album.update(album_params)
      flash[:notice] = "The album has been successfully updated"
    else
      flash[:alert] = "Ooops, something went wrong, album has not been saved. Repeat with other options"
    end
    redirect_to album_url(@username, @album)
  end

  def destroy
    photos_count = @album.photos.count
    if @album.destroy
      flash[:notice] = "Album '#{@album.title}' with #{photos_count} photos was deleted"
    else
      flash[:alert] = "Album was not deleted. Errors: #{@album.errors.full_messages}"
    end
    redirect_to albums_path(@username)
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    album = params.require(:album).permit(:title)
    album.merge(user_id: current_user.id)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def current_album
    Album.find(params[:album_id])
  end

  def default_album_title
    "Album ##{current_user.albums.size + 1}"
  end
end

app/views/albums/_album.html.haml
.thumbnail
  = link_to album_path(@username, album) do
    - if album.photos.any?
      = image_tag album.newest_photo_thumb
    - else
      = image_tag ''
  %hr
  .caption
    = link_to album_path(@username, album), class: 'btn btn-primary pull-right' do
      Photos
      %span.badge= album.photos_count
    %h2.h4= album.title

app/views/albums/_destroy.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{data: {dismiss: 'modal'}, 'aria-label' => 'Close'}
        %span{'aria-hidden' => 'true'} &times;
      %h1.h3 Delete Album
    .modal-body.text-center
      %h2.h3 This action will delete '#{@album.title}' with ALL photos inside it.
      %h2.h3.text-uppercase Are you sure???
    .modal-footer
      %button.btn.btn-default{data: {dismiss: 'modal'}} Really? Then NO!
      = link_to 'Delete', album_path(@username, @album), method: :delete, class: 'btn btn-danger'

app/views/albums/_edit.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{data: {dismiss: 'modal'}, 'aria-label' => 'Close'}
        %span{'aria-hidden' => 'true'} &times;
      %h1.h3 Change Title
    .modal-body
      = simple_form_for(current_album, url: album_path(@username, @album), method: :patch) do |f|
        = f.input :title, class: 'form-control'
        .modal-footer
          = f.button :submit

app/views/albums/_new.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{data: {dismiss: 'modal'}, 'aria-label' => 'Close'}
        %span{'aria-hidden' => 'true'} &times;
      %h1.h3 Create New Album
    .modal-body
      = simple_form_for(Album.new, url: albums_path, method: :post) do |f|
        = f.input :title, class: 'form-control', input_html: { value: default_album_title }
        .modal-footer
          = f.button :submit

app/views/albums/index.html.haml
%ol.breadcrumb
  %li
    %a{href: feed_url(@username)}= full_name_from_params(@username)
  %li.active Albums
- if @username == snake_case(current_user.full_name)
  %button.btn.btn-link{data: {toggle: 'modal', target: '#create-album'}} Create New Album

#create-album.modal.fade{tabindex: '-1', role: 'dialog'}
  = render 'albums/new'

.masonry
  = render @albums