config/routes.rb
Rails.application.routes.draw do
  scope ':username' do
    get 'feed' => 'users#feed'
    get 'following' => 'users#following'
    get 'followers' => 'users#followers'

    resources :albums, only: [:index, :show, :create, :update, :destroy]
    resources :albums, only: [] do
      resources :photos
    end

    resources :photos, only: [] do
      resources :comments, only: [:create, :destroy]
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrations: 'users/registrations'
  }

  get 'search' => 'users#index'
  resources :relationships, only: [:create, :destroy]

  get 'try' => 'static_pages#login_as_default_user'
  root 'static_pages#welcome'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  belongs_to :album
  mount_uploader :source, PhotoUploader
  has_many :comments, dependent: :destroy
  default_scope -> { order(updated_at: :desc) }

  validates :title, length: { maximum: 128 }
  validates :caption, length: { maximum: 512 }

  def original_url
    source.url
  end

  def thumb_url
    source.thumb.url
  end

  def album_title
    album.title
  end

  def comments_count
    comments.count
  end

  def owner_name
    user.full_name
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_album
  before_action :set_photo, only: [:show, :update, :destroy]
  before_action :set_username

  def index
    @photos = @album.photos
  end

  def show
    @comments = @photo.comments
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:notice] = "Photo #{@photo.title} has been successfully uploaded"
    else
      flash[:alert] = "Ooops, something went wrong, photo has not been saved. Repeat with other options"
    end
    redirect_to album_photo_path(@username, @photo.album, @photo)
  end

  def update
    if @photo.update(photo_params)
      flash[:notice] = "Photo #{@photo.title} has been successfully updated"
    else
      flash[:alert] = "Ooops, something went wrong, photo has not been saved. Repeat with other options"
    end
    redirect_to album_photo_path(@username, @photo.album, @photo)
  end

  def destroy
    if @photo.destroy
      flash[:notice] = "Photo '#{@photo.title}' was deleted"
    else
      flash[:alert] = "Photo was not deleted. Errors: #{@photo.errors.full_messages}"
    end
    redirect_to album_path(@username, @photo.album)
  end

  private

  def photo_params
    photo = params.require(:photo).permit(:title, :caption, :source, :remote_source_url)
    photo.merge(album_id: params[:album_id], user_id: current_user.id)
  end

  def set_album
    @album = Album.find(params[:album_id])
  end

  def set_photo
    @photo = @album.photos.find(params[:id])
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
  def default_photo_title
    Time.now.strftime '%d %b %Y'
  end

  def default_photo_caption
    "#{current_user.full_name} uploaded this photo for some reason"
  end
end

app/views/photos/_comment_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{data: {dismiss: 'modal'}, 'aria-label' => 'Close'}
        %span{'aria-hidden' => 'true'} &times;
      %h1.h3 Comment Photo
    .modal-body
      = simple_form_for(Comment.new, url: photo_comments_path(@username, @photo), method: :post) do |f|
        = f.input :body
        .modal-footer
          = f.button :submit

app/views/photos/_destroy.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{data: {dismiss: 'modal'}, 'aria-label' => 'Close'}
        %span{'aria-hidden' => 'true'} &times;
      %h1.h3 Delete Photo
    .modal-body.text-center
      %h2.h3 This action will delete '#{@photo.title}'.
      %h2.h3.text-uppercase Are you sure???
    .modal-footer
      %button.btn.btn-default{data: {dismiss: 'modal'}} Really? Then NO!
      = link_to 'Delete', album_photo_path(@username, @photo.album, @photo), method: :delete, class: 'btn btn-danger'

app/views/photos/_edit.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{data: {dismiss: 'modal'}, 'aria-label' => 'Close'}
        %span{'aria-hidden' => 'true'} &times;
      %h1.h3 Edit Photo
    .modal-body
      = simple_form_for(@photo, url: album_photo_path(@username, @photo.album, @photo), method: :patch, html: { multipart: true }) do |f|
        = f.input :title, class: 'form-control'
        = f.input :caption, class: 'form-control'
        = f.input :source, as: :file
        or
        = f.input :remote_source_url
        %hr
        %a.btn.btn-primary{href: "#", onclick: "return launchEditor('editableimage', '#{@photo.original_url}');"} Use photo editor
        .modal-footer
          = f.button :submit

app/views/photos/_new.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{data: {dismiss: 'modal'}, 'aria-label' => 'Close'}
        %span{'aria-hidden' => 'true'} &times;
      %h1.h3 Upload New Photo
    .modal-body
      = simple_form_for(Photo.new, url: album_photos_path(@username, @album.id), method: :post, html: { multipart: true }) do |f|
        = f.input :title, class: 'form-control', input_html: { value: default_photo_title }
        = f.input :caption, class: 'form-control', input_html: { value: default_photo_caption }
        = f.input :source, as: :file
        or
        = f.input :remote_source_url
        .modal-footer
          = f.button :submit

app/views/photos/_photo.html.haml
.thumbnail
  = link_to album_photo_path(@username, photo.album, photo) do
    = image_tag photo.thumb_url
  .caption
    %h2.h4= photo.title
    %p= photo.caption

app/views/photos/index.html.haml
%ol.breadcrumb
  %li
    %a{href: feed_url(@username)}= full_name_from_params(@username)
  %li
    %a{href: albums_url(@username)} Albums
  %li.active= @album.title
- if @username == snake_case(current_user.full_name)
  .dropdown
    %button.btn.btn-link.dropdown-toggle#actions{data: {toggle: 'dropdown'}, 'aria-hashpopup' => 'true', 'aria-expanded' => 'false'}
      Actions
      %span.caret
    %ul.dropdown-menu{'aria-labelledby' => 'actions'}
      %li
        %button.btn.btn-link{data: {toggle: 'modal', target: '#create-photo'}} Upload New Photo
      %li
        %button.btn.btn-link{data: {toggle: 'modal', target: '#edit-album'}} Change Album's Title
      %li
        %button.btn.btn-link{data: {toggle: 'modal', target: '#delete-album'}} Delete Album

#create-photo.modal.fade{tabindex: '-1', role: 'dialog'}
  = render 'photos/new'

#edit-album.modal.fade{tabindex: '-1', role: 'dialog'}
  = render 'albums/edit'

#delete-album.modal.fade{tabindex: '-1', role: 'dialog'}
  = render 'albums/destroy'

.masonry
  = render @photos

app/views/photos/show.html.haml
%ol.breadcrumb
  %li
    %a{href: feed_url(@username)}= full_name_from_params(@username)
  %li
    %a{href: albums_url(@username)} Albums
  %li
    %a{href: album_path(@username, @photo.album)}= @photo.album_title
  %li.active= @photo.title

#edit-photo.modal.fade{tabindex: '-1', role: 'dialog'}
  = render 'photos/edit'

#delete-photo.modal.fade{tabindex: '-1', role: 'dialog'}
  = render 'photos/destroy'

#comment-photo.modal.fade{tabindex: '-1', role: 'dialog'}
  = render 'photos/comment_form'

#view-photo
  .panel.panel-default
    .panel-body
      .row
        .col-sm-6.col-md-8.col-lg-9
          = link_to @photo.original_url, target: '_blank' do
            = image_tag @photo.original_url, id: "editableimage"
        .col-sm-6.col-md-4.col-lg-3
          %h2.h4= @photo.title
          %p= @photo.caption
          - if @username == snake_case(current_user.full_name)
            .text-right
              %button.btn.btn-link{data: {toggle: 'modal', target: '#edit-photo'}} Edit Photo
              %button.btn.btn-link{data: {toggle: 'modal', target: '#delete-photo'}} Delete Photo
          %hr
          %button.btn.btn-primary{data: {toggle: 'modal', target: '#comment-photo'}} Leave a Comment
      .row
        .col-sm-6.col-md-8.col-lg-9
          #comments
            %hr
            - if @comments.empty?
              %p No comments yet
            - else
              = render @comments